// A curated list of common icons from @tabler/icons-react
// We map the string name to the actual component for easy rendering.

import {
  IconHome,
  IconUser,
  IconSettings,
  IconPhoto,
  IconMessage,
  IconBell,
  IconCalendar,
  IconSearch,
  IconX,
  IconCheck,
  IconChevronDown,
  IconChevronUp,
  IconChevronLeft,
  IconChevronRight,
  IconPlus,
  IconMinus,
  IconTrash,
  IconEdit,
  IconCopy,
  IconFile,
  IconFolder,
  IconBox,
  IconGift,
  IconStar,
  IconHeart,
  IconThumbUp,
  IconThumbDown,
  IconSun,
  IconMoon,
  IconCloud,
  IconLock,
  IconWorld,
  IconMail,
  IconLink,
  IconAlertTriangle,
  IconPlayerPlay,
  IconPlayerPause,
  IconPlayerStop,
  type IconProps as TablerIconsProps,
} from "@tabler/icons-react";
import { FC } from "react";

// For convenience, define a type for our icon components
export type IconComponent = FC<TablerIconsProps>;

// The main mapping object
export const iconMap: Record<string, IconComponent> = {
  IconHome,
  IconUser,
  IconSettings,
  IconPhoto,
  IconMessage,
  IconBell,
  IconCalendar,
  IconSearch,
  IconX,
  IconCheck,
  IconChevronDown,
  IconChevronUp,
  IconChevronLeft,
  IconChevronRight,
  IconPlus,
  IconMinus,
  IconTrash,
  IconEdit,
  IconCopy,
  IconFile,
  IconFolder,
  IconBox,
  IconGift,
  IconStar,
  IconHeart,
  IconThumbUp,
  IconThumbDown,
  IconSun,
  IconMoon,
  IconCloud,
  IconLock,
  IconWorld,
  IconMail,
  IconLink,
  IconAlertTriangle,
  IconPlayerPlay,
  IconPlayerPause,
  IconPlayerStop,
};

// An array of just the names for easy iteration
export const iconNames = Object.keys(iconMap);
