import type { Metadata } from "next";
import "./globals.css";
import {
  SidebarInset,
  SidebarInsetHeader,
  SidebarMain,
  SidebarWrapper,
} from "@/components/ui/sidebar";
import { SidebarDemo } from "@/components/dashboard/dashboard-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <SidebarWrapper>
          <SidebarDemo />
          <SidebarMain>
            <SidebarInsetHeader>
              <div className="h-14" />
            </SidebarInsetHeader>
            <SidebarInset>{children}</SidebarInset>
          </SidebarMain>
        </SidebarWrapper>
      </body>
    </html>
  );
}
